#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias ll='ls -alh'
alias la='ls -A'

alias ips="sudo ifconfig | grep 'inet addr:' | cut -d: -f2 | cut -d\  -f1"

export PYTHONSTARTUP="$HOME/.pyrc"
export LESS='-R -I'
export LESSOPEN='|~/.lessfilter %s'

alias e='COLORTERM= emacs -nw'
# https://stackoverflow.com/questions/72803319/the-display-is-wrong-when-using-iterm2-screen-emacs-on-macos-monterey

alias ee='HOME=~/spacemacs/ e'
alias g='git'
alias m='make'
alias f='fg'
alias gst='git st'
alias gitamendstudent='git commit --amend -s --date="$(date -R)"'
alias rgrep='grep -r -n --colour'
alias psgrep='ps aux | grep'
alias diff='colordiff'
alias gitk='gitk --all'
alias py3='python3'
alias clntild='find . -type f -name \*~ -delete'
alias irc='ssh -t vps screen -rd weechat'
alias kirc='ps h -C "ssh vps" -o pid | xargs kill'
alias mux='tmuxinator'
alias webserv='python3 -m http.server 8000'
alias osm='telnet mapscii.me'
alias vlcgif='vlc --demux=avformat'
alias r='ranger'

# monitor disk I/O
alias iotop='sudo iotop'

alias rm='rm -I'
#alias mv='mv -f --backup=none'

alias weather='curl --silent http://wttr.in/amsterdam'

# enables sudo to expand on alias
alias sudo='sudo '

export EDITOR='emacs -nw'
export VISUAL="$EDITOR"

# mutt background fix
COLORFGBG="default;default"

export PATH=$PATH:~/bin:~/.local/bin

export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
export JDK_HOME="/usr/lib/jvm/java-17-openjdk-amd64"

export ANDROID_HOME="/opt/android"
export PATH=${PATH}:${ANDROID_HOME}/cmdline-tools/latest/bin
export PATH=${PATH}:${ANDROID_HOME}/tools/bin
export PATH=${PATH}:${ANDROID_HOME}/platform-tools
export PATH=${PATH}:${ANDROID_HOME}/build-tools/28.0.3

unset GREP_COLOR
export GREP_COLORS=7

export TERM=xterm-256color

setopt no_share_history

# disables auto-correct
unsetopt correct_all

# autocomplete hidden files without specifying the dot
_comp_options+=(globdots)

alias tpb="ssh -N -D 2001 vps & firefox -no-remote -P socks-vps 'https://thepiratebay.org' && kill '%1'"
alias proxy-rpi="ssh -N -D 2001 pimatt & firefox -no-remote -P socks-vps 'https://duckduckgo.com' && kill '%1'"
alias biggestfiles='/usr/bin/du -a . 2>/dev/null | sort -n -r | head -n 100'

# fix default alias using python2
alias http-serve='python3 -m http.server'

# do me some python doc
alias pd='pydoc3'

# xfce muscle memory
alias file-roller='xarchiver'

# Set up fzf key bindings and fuzzy completion
export FZF_DEFAULT_OPTS="--layout=reverse --inline-info --border --tmux"
source <(fzf --zsh)

# ripgrep: pipe with less when output is a terminal
rg() {
    if [ -t 1 ]; then
        command rg --hidden -p "$@" | less -RMF
    else
        command rg "$@"
    fi
}

# Completions for kubectl
[[ /home/matthieu/.local/bin/kubectl ]] && source <(kubectl completion zsh)
