#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias ll='ls -alh'
alias la='ls -A'

alias ips="sudo ifconfig | grep 'inet addr:' | cut -d: -f2 | cut -d\  -f1"

export PYTHONSTARTUP="$HOME/.pyrc"
export LESS='-R'
export LESSOPEN='|~/.lessfilter %s'

alias e='emacs -nw'
alias g='git'
alias m='make'
alias gst='git st'
alias gitamendstudent='git commit --amend -s --date="$(date -R)"'
alias rgrep='grep -r -n --colour'
#export GREP_OPTIONS="-n --color"
alias psgrep='ps aux | grep'
alias rgrepds='rgrep --exclude-dir=.git --exclude-dir=cache --exclude-dir=testdata --exclude=\*.pyc'
alias lynx='lynx -lss ~/.lynx.lss'
alias diff='colordiff'
alias docker='sudo docker'
alias cleandocker='(sudo docker.io ps -a | tail -n +2 | awk "{print $1}" | xargs sudo docker.io rm) && (sudo docker.io images | tail -n +2 | awk "{print $3}" | xargs sudo docker.io rmi)'
alias gitk='gitk --all'
alias py3='python3'
alias clntild='find . -name \*~ -delete'

alias kirc='ps h -C "ssh vps" -o pid | xargs kill'

alias webserv='python -m SimpleHTTPServer 8000'
alias php-serve-here='php -S localhost:8000'

# monitor disk I/O
alias iotop='sudo iotop'

alias rm='rm -I'
alias mv='mv -f --backup=none'

alias weather='curl --silent http://wttr.in/grenoble | head -7'

# enables sudo to expand on alias
alias sudo='sudo '

export EDITOR='emacs -nw'
export VISUAL='$EDITOR'

# mutt background fix
COLORFGBG="default;default"

export PATH=$PATH:~/bin

export PATH=$PATH:/home/matthieu/software/hadoop/hadoop-2.6.0/bin

export PATH=$PATH:/opt/android-sdk-linux/tools:/opt/android-sdk-linux/platform-tools

export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
export JDK_HOME="/usr/lib/jvm/java-7-openjdk-amd64"

export ANDROID_HONE="/opt/android-sdk-linux"

unset GREP_COLOR
export GREP_COLORS=7

export TERM=xterm-256color

setopt no_share_history

# disables auto-correct
unsetopt correct_all
